### ISSUE TITLE
执行felix sshw启动报错

### ISSUE THREAD

**Issue by zhengerfu** [dejavuzhou/felix#5]
root@debian:/opt/goproject/src/github.com/dejavuzhou/felix# felix sshw
panic: interface conversion: interface {} is string, not []uint8 [recovered]
	panic: interface conversion: interface {} is string, not []uint8

goroutine 1 [running]:
github.com/jinzhu/gorm.(*Scope).callCallbacks.func1(0xc00016d900)
	/opt/goproject/src/github.com/jinzhu/gorm/scope.go:884 +0xb0
panic(0xc85400, 0xc00018d080)
	/opt/soft/go/src/runtime/panic.go:522 +0x1b5
github.com/dejavuzhou/felix/models.(*JsonArrayUint).Scan(0xc00008c560, 0xc37ce0, 0xc0003f0d30, 0x7ff00783d238, 0xc00008c560)
	/opt/goproject/src/github.com/dejavuzhou/felix/models/j_array_uint.go:16 +0xa3
database/sql.convertAssignRows(0xcc2d20, 0xc00008c560, 0xc37ce0, 0xc0003f0d30, 0xc00016da00, 0xc00008c560, 0x0)
	/opt/soft/go/src/database/sql/convert.go:378 +0x189a
database/sql.convertAssignRows(0xc000066a00, 0xc000010aa0, 0xc37ce0, 0xc0003f0d30, 0xc00016da00, 0x0, 0x0)
	/opt/soft/go/src/database/sql/convert.go:421 +0xf2f
database/sql.(*Rows).Scan(0xc00016da00, 0xc0000c22a0, 0xe, 0xe, 0xc000074798, 0xc000010aa0)
	/opt/soft/go/src/database/sql/sql.go:2955 +0x212
github.com/jinzhu/gorm.(*Scope).scan(0xc00016d900, 0xc00016da00, 0xc0000c2000, 0xe, 0xe, 0xc00016db00, 0xf, 0x10)
	/opt/goproject/src/github.com/jinzhu/gorm/scope.go:532 +0x55b
github.com/jinzhu/gorm.queryCallback(0xc00016d900)
	/opt/goproject/src/github.com/jinzhu/gorm/callback_query.go:79 +0x5f8
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc00016d900, 0xc0001a1520, 0x3, 0x4, 0x0)
	/opt/goproject/src/github.com/jinzhu/gorm/scope.go:888 +0x88
github.com/jinzhu/gorm.(*DB).First(0xc0003e7110, 0xcec7e0, 0xc0001aae10, 0x0, 0x0, 0x0, 0xc68ce0)
	/opt/goproject/src/github.com/jinzhu/gorm/main.go:331 +0x128
github.com/jinzhu/gorm.(*DB).FirstOrCreate(0xc0003e7110, 0xcec7e0, 0xc0001aae10, 0x0, 0x0, 0x0, 0xc0003e7110)
	/opt/goproject/src/github.com/jinzhu/gorm/main.go:425 +0x9c
github.com/dejavuzhou/felix/models.(*User).CreateInitUser(0xc0001aae10, 0xc0001aae10, 0x9)
	/opt/goproject/src/github.com/dejavuzhou/felix/models/m_users.go:107 +0xfd
github.com/dejavuzhou/felix/models.CreateSqliteDB(0x0)
	/opt/goproject/src/github.com/dejavuzhou/felix/models/db.go:41 +0x5a8
github.com/dejavuzhou/felix/cmd.initFunc()
	/opt/goproject/src/github.com/dejavuzhou/felix/cmd/root.go:53 +0x2c
github.com/spf13/cobra.(*Command).preRun(0x1861240)
	/opt/goproject/src/github.com/spf13/cobra/command.go:856 +0x49
github.com/spf13/cobra.(*Command).execute(0x1861240, 0x18ca6c8, 0x0, 0x0, 0x1861240, 0x18ca6c8)
	/opt/goproject/src/github.com/spf13/cobra/command.go:792 +0x146
github.com/spf13/cobra.(*Command).ExecuteC(0x185ecc0, 0xc000021200, 0x18a9680, 0x0)
	/opt/goproject/src/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/opt/goproject/src/github.com/spf13/cobra/command.go:864
github.com/dejavuzhou/felix/cmd.Execute(0x0, 0x0, 0x0, 0x0)
	/opt/goproject/src/github.com/dejavuzhou/felix/cmd/root.go:37 +0x7c
main.main()
	/opt/goproject/src/github.com/dejavuzhou/felix/main.go:8 +0x51

**Comment by JJJJJJJerk** [comment]
应该是sqlite3 json 字段的问题, 删除 users 这种表 让gorm自动迁移一次 或者执行 felix flush 命令

**Comment by mojocn** [comment]
执行felix clean 删除之前的sqlite数据
