### ISSUE TITLE
felix sshw 报错

### ISSUE THREAD

**Issue by lifegit** [dejavuzhou/felix#7]
`felix sshw                                                                                          
panic: interface conversion: interface {} is string, not []uint8 [recovered]
        panic: interface conversion: interface {} is string, not []uint8

goroutine 1 [running]:
github.com/jinzhu/gorm.(*Scope).callCallbacks.func1(0xc0006a3200)
        /Users/yxs/GolandProjects/src/github.com/jinzhu/gorm/scope.go:884 +0xb3
panic(0x48ac640, 0xc0006b4600)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/dejavuzhou/felix/models.(*JsonArrayUint).Scan(0xc0001518c0, 0x485fd00, 0xc000069840, 0x6294200, 0xc0001518c0)
        /Users/yxs/GolandProjects/src/github.com/dejavuzhou/felix/models/j_array_uint.go:16 +0xa3
database/sql.convertAssign(0x4901cc0, 0xc0001518c0, 0x485fd00, 0xc000069840, 0xc0001518c0, 0x16)
        /usr/local/Cellar/go/1.11/libexec/src/database/sql/convert.go:341 +0x17c8
database/sql.convertAssign(0xc0001ccbc0, 0xc000444eb0, 0x485fd00, 0xc000069840, 0x0, 0x0)
        /usr/local/Cellar/go/1.11/libexec/src/database/sql/convert.go:384 +0xc14
database/sql.(*Rows).Scan(0xc0006a3300, 0xc000128400, 0x10, 0x10, 0xc0000ac0b0, 0x16)
        /usr/local/Cellar/go/1.11/libexec/src/database/sql/sql.go:2932 +0x1e7
github.com/jinzhu/gorm.(*Scope).scan(0xc0006a3200, 0xc0006a3300, 0xc00044df00, 0x10, 0x10, 0xc000128300, 0x11, 0x20)
        /Users/yxs/GolandProjects/src/github.com/jinzhu/gorm/scope.go:532 +0x499
github.com/jinzhu/gorm.queryCallback(0xc0006a3200)
        /Users/yxs/GolandProjects/src/github.com/jinzhu/gorm/callback_query.go:79 +0x523
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc0006a3200, 0xc0001c7600, 0x3, 0x4, 0x0)
        /Users/yxs/GolandProjects/src/github.com/jinzhu/gorm/scope.go:888 +0x88
github.com/jinzhu/gorm.(*DB).First(0xc0006aaea0, 0x4911ba0, 0xc000691c20, 0x0, 0x0, 0x0, 0x48909c0)
        /Users/yxs/GolandProjects/src/github.com/jinzhu/gorm/main.go:331 +0x10d
github.com/jinzhu/gorm.(*DB).FirstOrCreate(0xc0006aaea0, 0x4911ba0, 0xc000691c20, 0x0, 0x0, 0x0, 0xc0006aaea0)
        /Users/yxs/GolandProjects/src/github.com/jinzhu/gorm/main.go:425 +0x9c
github.com/dejavuzhou/felix/models.(*User).CreateInitUser(0xc000691c20, 0xc000691c20, 0xa)
        /Users/yxs/GolandProjects/src/github.com/dejavuzhou/felix/models/m_users.go:105 +0x105
github.com/dejavuzhou/felix/models.CreateSqliteDB(0x0)
        /Users/yxs/GolandProjects/src/github.com/dejavuzhou/felix/models/db.go:41 +0x532
github.com/dejavuzhou/felix/cmd.initFunc()
        /Users/yxs/GolandProjects/src/github.com/dejavuzhou/felix/cmd/root.go:53 +0x2c
github.com/spf13/cobra.(*Command).preRun(0x51fd020)
        /Users/yxs/GolandProjects/src/github.com/spf13/cobra/command.go:856 +0x49
github.com/spf13/cobra.(*Command).execute(0x51fd020, 0x522d938, 0x0, 0x0, 0x51fd020, 0x522d938)
        /Users/yxs/GolandProjects/src/github.com/spf13/cobra/command.go:792 +0x148
github.com/spf13/cobra.(*Command).ExecuteC(0x51faaa0, 0xc0000e3f58, 0x46bfe81, 0xc00044d100)
        /Users/yxs/GolandProjects/src/github.com/spf13/cobra/command.go:914 +0x2f8
github.com/spf13/cobra.(*Command).Execute(0x51faaa0, 0xc0000e3f58, 0x46bff6e)
        /Users/yxs/GolandProjects/src/github.com/spf13/cobra/command.go:864 +0x2b
github.com/dejavuzhou/felix/cmd.Execute(0x0, 0x0, 0x0, 0x0)
        /Users/yxs/GolandProjects/src/github.com/dejavuzhou/felix/cmd/root.go:37 +0x77
main.main()
        /Users/yxs/GolandProjects/src/github.com/dejavuzhou/felix/main.go:8 +0x51
`

另外找到相同的问题 https://github.com/dejavuzhou/felix/issues/5
没有felix flush 这个指令
felix flush    
Error: unknown command "flush" for "felix"
Run 'felix --help' for usage.
unknown command "flush" for "felix"

**Comment by lifegit** [comment]
felix ginbro -u root -p passs -c utf8 -a 127.0.0.1:3306 -n blog -d=test.blog

也是如上报错

**Comment by mojocn** [comment]
你是不是 之前安装过felix 这个程序?  我在sqlite3中定义了一个json 类型的字段.  我在Windows10 和linux上是没有报错的,   你电脑是mac?

**Comment by mojocn** [comment]
看一下是不是这个原因 https://github.com/dejavuzhou/felix/issues/6

**Comment by lifegit** [comment]
@mojocn  mac,没有装过felix

**Comment by lifegit** [comment]
felix clean 也是出现上述错误

**Comment by mojocn** [comment]
你会使用gorm 的mysql  不要不你自己缓存mysql数据库吧  我mac(太旧了)放在家里面了,

**Comment by lifegit** [comment]
go install 已经成功，但是felix sshw 就不行了。应该不是 #6的问题

**Comment by lifegit** [comment]
我该如何做？

**Comment by mojocn** [comment]
https://github.com/dejavuzhou/felix/commit/55a688c3aebadc35061eb2310d339972001d53ee git pull 一下 再试一下啊

**Comment by mojocn** [comment]
rm -rf ~/.felix.db 这个文件

**Comment by lifegit** [comment]
感谢，重新 git pull ，然后 go install ，问题解决
