### ISSUE TITLE
ginbro 的 jwt

### ISSUE THREAD

**Issue by lifegit** [dejavuzhou/felix#8]
![image](https://user-images.githubusercontent.com/33006878/61129500-1ea45e80-a4e7-11e9-81c7-98753b7acbda.png)

jwt在解析Authorization这个header时，报错

**Comment by JJJJJJJerk** [comment]
你把token 复制出来 到这里检查一下 https://jwt.io/ 看是否是合法token

**Comment by JJJJJJJerk** [comment]
我ginbro 的代码模板 可以在优化一下,  特别是jwt 中间件和 分页器

**Comment by lifegit** [comment]
ginbro 生成后的代码中，有几个问题想问下：
1. jwt生成的token，其中value通过memoryStore来实现了内存持久化，实际上返回给客户端的token只有一个key，当客户端再访问时，通过这个key再去memoryStore取出实际数据，这样的原理好想又回到了session的概念，而jwt的思想不是抛弃服务端而用客户端保存一些简单数据吗？您代码中使用memoryStore来实现了内存持久化，分布式后，每台机器的token数据还是独立的，没法共享，为什么不用redis呢？

2. viper ，这个工具，每次进行get时，是否有缓存呢？比如上次get过这个val，下次get时候是从缓存中拿还是重新io读*.toml文件呢？

3. models 文件夹下的 helper.go 中的 crudOne crudAll  函数没有指定查询字段，没有.Select(),查询的时候将会select * from tb ，这将影响到sql性能。 
`func crudOne(m interface{}, one interface{}) (err error) {
	// 启用Logger，显示详细日志
	db.LogMode(true)

	// 禁用日志记录器，不显示任何日志
	db.LogMode(false)
	if db.Debug().Where(m).First(one).RecordNotFound() {
		return errors.New("resource is not found")
	}
	// var list = []string{KeysName, KeysState}
	// if db.Debug().Select(list).Where(m).First(one).RecordNotFound() {
	//	 return errors.New("resource is not found")
	// }
	return nil
}`


最后感谢您提供这么好的工具让我学习，希望这几个问题能分别解答下我，谢谢您。

**Comment by JJJJJJJerk** [comment]
1. jwt 这个我在felix已经优化了,  ginbro 字符串模板没有更新
2. viper 配置文件initfunc 中加载到内存中了. 以后去get 配置可以 不会重复加载配置文件.
3. select 默认查询全部字段, sql 查询性能主要是瓶颈 索引和join ,select field 影响比较小
ginbro 代码模板我有时间会在更新的

**Comment by lifegit** [comment]
1.关于无效字段的处理
举例：
user表字段：id,username,password,name,age
假设api只需要通过id获取name与age返回数据，但是crudOne 方法中没有指定.Select()，会将整行select  * from user，那么将会导致password被查询,我看到代码中的处理是 m.password = "",在返回json的时候password字段将会变空：{"id":1,"username":"123456","password":"","name":"mrs","age":"18"}，而我希望既然不需要password字段与username与别的字段(真实情况不需要的字段可能更多更多，甚至长达十几个)，这样浪费了数据库的io，也浪费的服务器的带宽，数据库管理员也不愿意select *，希望select查询的时候只查询有关的字段，并且返回json的时，不需要的字段可以不输出，例：{"name":"mrs","age":"18"}，有什么好的建议吗？

2. ginbro生成出来后的代码，肯定还要进行更改，这样就导致与swagger api还有models的struct不一致，有没有什么办法，根据handlers与models重新生成swagger api与struct?
